version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5440:5432
    env_file:
      - ./.env

volumes:
  postgres_data: